# Copyright (c) Boucher Lab. All rights reserved.
# Licensed under the GNU license.
# See LICENSE file in the repository root for full license information.

################################################################################
#                                Imports                                       #
################################################################################

#import os, ast, glob
from snakemake.utils import min_version

#min_version("7.12.1")

################################################################################
#                       Config File & Shorthands                               #
################################################################################

configfile: "config/config.yaml"

EMAIL = config["email"]
RUNID = config["run_id"]
OUTPUT = config["output"]
OUTDIR = OUTPUT + RUNID
LOGDIR = f"{OUTDIR}/snakemake_logs"
BENCHDIR = f"{OUTDIR}/snakemake_benchmarks"
BARCODES = config["barcodes"]
READS = config["reads"]
SAMPLES = [f for f in os.listdir(READS) if not f.startswith(".")]
DATABASES = config["databases"]
HOST = config["host_organism"]
HOST_FILE = config["host_genome"]
SIMILARITY = config["similarity_threshold"]
CROPLEN = config["crop_len"]
#CUTOFF = config["sftclp_cutoff"]

ALL_INPUT = [
#    f"{OUTDIR}/on_target_stats.tsv",
    f"{OUTDIR}/merged_overlapped_mges_info.csv",
    f"{OUTDIR}/no_header_telcomb_stats.csv",
    f"{OUTDIR}/telcomb_stats.csv",
    expand(f"{OUTDIR}/{{sample}}_raw_reads_lengths.json", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_non_host_reads_lengths.json", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_pre_dedup_rl.tsv", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_post_dedup_rl.tsv", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_start_read_count.txt", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_non_host_read_count.txt", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_hard_trim_count.txt", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_chimeric_count.txt", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_deduplicated_amr_features.csv", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_deduplicated_amr_richness.csv", sample=SAMPLES),
#    expand(f"{OUTDIR}/{{sample}}_ato_megares.sam", sample=SAMPLES),
#    expand(f"{OUTDIR}/{{sample}}_ato_mges.sam", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_deduplicated_colocalizations.csv", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_deduplicated_colocalizations_richness.csv", sample=SAMPLES),
#    expand(f"{OUTDIR}/{{sample}}_non_host.gz_genes_list.xlsx", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_deduplicated_mobilome.csv", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_deduplicated_overlapped_mges.csv", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_read_lengths_hist.pdf", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_colocalizations_plots.pdf", sample=SAMPLES),
    expand(f"{OUTDIR}/{{sample}}_telcomb_stats.csv", sample=SAMPLES),
    #f"{OUTDIR}/violin_plot_all_samples.svg",
    #f"{OUTDIR}/heatmap_all_samples.svg",
#    expand(f"{OUTDIR}/{{sample}}_add_sample_info.done", sample=SAMPLES),
]


rule all:
    input:
        ALL_INPUT,


include: "rules/concat_parts.smk"


include: "rules/trim_reads.smk"


include: "rules/start_read_count.smk"


include: "rules/non_host_read_count.smk"


include: "rules/trim_counts.smk"


include: "rules/deduplicate.smk"


include: "rules/dup_read_lengths.smk"


include: "rules/host_removal.smk"


include: "rules/host_removal_stats.smk"


#include: "rules/stats_alignment.smk"


#include: "rules/on_target_stats.smk"


include: "rules/megares_alignment.smk"


include: "rules/mges_alignment.smk"


#include: "rules/pass_config.smk"


include: "rules/read_lengths_json.smk"


include: "rules/overlap.smk"


include: "rules/resistome_mobilome.smk"


include: "rules/colocalization.smk"


include: "rules/colocalization_plot.smk"


include: "rules/read_length_plot.smk"


include: "rules/telcomb_stats.smk"


onsuccess:
    shell(f"bash workflow/scripts/log_cleanup.sh {LOGDIR}")

#include: "rules/violin_plot.smk"


#include: "rules/heatmap.smk"


#include: "rules/add_sample_info.smk"
