# Copyright (c) Boucher Lab. All rights reserved.
# Licensed under the GNU license.
# See LICENSE file in the repository root for full license information.

name: pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - samtools=1.9
  - biopython
  - pysam
  - scipy
  - scikit-learn
  - pandas
  - tqdm